Add cart functionality
kuli00/big-commerce pull request #37
Opened 2021-09-08 09:12 UTC by marcinszablowski

2021-09-08 09:35 UTC, KajBialas requested changes

2021-09-08 09:35 UTC, KajBialas commented on pages/api/cartItem.ts
> +  }
Please eliminate this to form: `const cartUrl = cartId ? cartUrl1 : cartUrl2`

2021-09-08 09:35 UTC, KajBialas commented on pages/api/cartItem.ts
> +    validateStatus: () => true,
This is probably for extend?

2021-09-08 09:35 UTC, KajBialas commented on pages/api/products.ts
> +    url: 'https://api.bigcommerce.com/stores/cvfzp58ivy/v3/catalog/products?include=images,variants',
URLs should be defined as consts

2021-09-08 09:35 UTC, KajBialas commented on pages/cart.tsx
> +  }, []);
Please create custom hook for this logic

2021-09-08 09:35 UTC, KajBialas commented on pages/cart.tsx
> +    const getCartData = async () => {
For api call good to create service.

2021-09-08 09:35 UTC, KajBialas commented on pages/cart.tsx
> +  const [cartData, setCartData] = useState([]);
In my oppinion we need to support loading and error status. Good to create `useReducer` for api calls state managment.

2021-09-08 09:35 UTC, KajBialas commented on pages/products/[product].tsx
> +              infoCard.current.classList.remove('active');
Maybe good move this to function and add memoization for this?

2021-09-08 09:35 UTC, KajBialas commented on pages/products/[product].tsx
> +                      className="btn btn-solid"
Maybe better to use styled components for all styled elements?

2021-09-08 09:35 UTC, KajBialas commented on src/components/Header/Header.tsx
> +                          color: '#797979',
Not describe styles as inline.

2021-09-08 09:35 UTC, KajBialas commented on src/components/InfoBox/InfoBox.tsx
> +`;
Styles should be in separated file

2021-09-08 10:07 UTC, kuli00 commented on pages/api/cartItem.ts
> +    validateStatus: () => true,
I assume this is because axios by default throws an error if status returned from api is other than `2xx`.

2021-09-08 11:09 UTC, marcinszablowski commented on pages/products/[product].tsx
> +                      className="btn btn-solid"
Yes. We used a ready-to-use theme for this demo to save time. We plan to move all styles to styled components.

2021-09-08 11:13 UTC, marcinszablowski commented on src/components/Header/Header.tsx
> +                          color: '#797979',
This is moved code. We needed quick overwrite of theme's styles. We will get rid of it once we will rewrite it to styled components and styled icons.

2021-09-13 11:43 UTC, kuli00 approved these changes

2021-09-13 14:57 UTC, merged